/**
 * Usage hypotheses, stated as falsifiable claims.
 *
 * Every layout decision in this product is generated by one question: what is
 * the unit of work on this screen, and how many does the hiring manager touch
 * per session? These are the answers, written down so a reviewer can disagree
 * with a number rather than with a vibe.
 */

export type ScreenId = 'search' | 'candidates' | 'outreach';
export type VariantId = 'a' | 'b' | 'c';

export interface ScreenUsage {
  unit: string;
  touches: string;
  dwell: string;
  verb: string;
  /** The thing this screen's layout must not get wrong. */
  stake: string;
}

export const SCREEN_USAGE: Record<ScreenId, ScreenUsage> = {
  search: {
    unit: 'one search configuration',
    touches: '1 per role',
    dwell: '5–10 min',
    verb: 'Specify',
    stake:
      'Filters fail invisibly. A slightly wrong one does not raise an error — it ' +
      'produces a list missing people you will never know about.',
  },
  candidates: {
    unit: 'one candidate',
    touches: '~110 scanned, ~15 opened',
    dwell: '3s scan · 60s read',
    verb: 'Reject',
    stake:
      '110 in, 9 out. This is a rejection machine, not a reading room — but ' +
      'rejection made too cheap becomes careless rejection.',
  },
  outreach: {
    unit: 'one pending action',
    touches: '~6 per session',
    dwell: '30s',
    verb: 'Decide',
    stake:
      'Six items need a decision. Success is emptying the queue, not browsing it.',
  },
};

export interface RegionUsage {
  /** Matches a `data-usage` attribute in the layout. */
  id: string;
  label: string;
  /** 0–5, rendered as a dot band. */
  frequency: number;
  touches: string;
  dwell: string;
  optimisedFor: string;
  costIfWrong: string;
}

export const REGION_USAGE: Record<ScreenId, RegionUsage[]> = {
  search: [
    {
      id: 'role',
      label: 'Role brief',
      frequency: 2,
      touches: '1–2×',
      dwell: '2 min',
      optimisedFor: 'Getting intent in once, in the manager’s own words',
      costIfWrong: 'Ema parses the wrong role and every downstream step inherits it',
    },
    {
      id: 'filters',
      label: 'Filters',
      frequency: 1,
      touches: '1× per search',
      dwell: '4 min',
      optimisedFor: 'Getting the eligible pool right first time',
      costIfWrong: 'Invisible failure — good people never appear and nobody finds out',
    },
    {
      id: 'scorecard',
      label: 'Scorecard',
      frequency: 2,
      touches: '2–3×',
      dwell: '3 min',
      optimisedFor: 'Stating what good looks like before seeing anyone',
      costIfWrong: 'Ranking is arbitrary, so the list cannot be trusted or argued with',
    },
    {
      id: 'reach',
      label: 'Estimated reach',
      frequency: 3,
      touches: '~8×',
      dwell: '5s',
      optimisedFor: 'Knowing the pool is sane before committing two minutes',
      costIfWrong: 'Over-constrained search discovered only after it finishes',
    },
    {
      id: 'preview',
      label: 'Live preview',
      frequency: 5,
      touches: 'every filter change',
      dwell: '3s',
      optimisedFor: 'Replacing an abstract count with actual people',
      costIfWrong: 'Back to guessing whether the filters mean what you think',
    },
  ],

  candidates: [
    {
      id: 'score',
      label: 'Score cell',
      frequency: 5,
      touches: '~110×',
      dwell: '3s',
      optimisedFor: 'Rejecting confidently without opening anything',
      costIfWrong: 'The screen degrades into a list of names',
    },
    {
      id: 'signals',
      label: 'Signals',
      frequency: 3,
      touches: '~110×',
      dwell: '<1s',
      optimisedFor: 'Catching stale, gate-failed and duplicate cases in peripheral vision',
      costIfWrong: 'Outreach wasted on people who cannot be reached',
    },
    {
      id: 'evidence',
      label: 'Evidence',
      frequency: 4,
      touches: '~15×',
      dwell: '60s',
      optimisedFor: 'Defending a shortlist decision with a quotable source',
      costIfWrong: 'Research shows hover-only evidence goes unread — the score becomes a black box',
    },
    {
      id: 'rail',
      label: 'Ranking controls',
      frequency: 1,
      touches: '1–2×',
      dwell: '90s',
      optimisedFor: 'Repairing a wrong scorecard after seeing real results',
      costIfWrong: 'The manager blames the candidates instead of the criteria',
    },
    {
      id: 'bulk',
      label: 'Bulk actions',
      frequency: 2,
      touches: '2–3×',
      dwell: '10s',
      optimisedFor: 'Acting on a decision already made across many rows',
      costIfWrong: 'Shortlisting becomes one-at-a-time clicking',
    },
  ],

  outreach: [
    {
      id: 'bulk',
      label: 'Bulk actions',
      frequency: 2,
      touches: '1–2×',
      dwell: '8s',
      optimisedFor: 'Clearing a whole stage at once — approve every ready draft, close out every non-reply',
      costIfWrong: 'Six identical decisions become six separate trips through the queue',
    },
    {
      id: 'next-action',
      label: 'Next action',
      frequency: 5,
      touches: '~6×',
      dwell: '5s',
      optimisedFor: 'Knowing what to do without opening the row',
      costIfWrong: 'The queue becomes a status board you browse instead of clear',
    },
    {
      id: 'grouping',
      label: 'Needs you / In flight',
      frequency: 4,
      touches: 'every visit',
      dwell: '2s',
      optimisedFor: 'Opening on the work rather than on the pipeline',
      costIfWrong: 'Waiting work hides among work that needs you — Front’s stated bug',
    },
    {
      id: 'detail',
      label: 'Detail pane',
      frequency: 4,
      touches: '~6×',
      dwell: '30s',
      optimisedFor: 'Acting on the item in place, not reporting on it',
      costIfWrong: 'Toast-driven UI — the bug already fixed twice in this build',
    },
    {
      id: 'stats',
      label: 'Stat strip',
      frequency: 2,
      touches: '2×',
      dwell: '3s',
      optimisedFor: 'Shape of the pipeline at a glance, and as a filter',
      costIfWrong: 'No sense of whether outreach is healthy or stalled',
    },
  ],
};

export const VARIANTS: Record<ScreenId, { id: VariantId; name: string; bet: string; sacrifice: string; steals: string }[]> = {
  search: [
    { id: 'a', name: 'Form + reach rail', bet: 'Everything visible at once is best for revision.', sacrifice: 'Feedback is an abstract count, not people.', steals: 'Current build' },
    { id: 'b', name: 'Conversational', bet: 'Ask only what changes who is eligible; infer the rest.', sacrifice: 'Revising filter #7 means scrolling a thread.', steals: 'Juicebox NL → reviewable spec' },
    { id: 'c', name: 'Live preview', bet: 'Filters fail invisibly, so show real people as you tune.', sacrifice: 'Scorecard collapses to a summary.', steals: 'SeekOut / Juicebox realtime population' },
  ],
  candidates: [
    { id: 'a', name: 'Table + drawer', bet: 'Density wins for a rejection machine.', sacrifice: 'Evidence sits behind hover, where research says it goes unread.', steals: 'LinkedIn slide-in' },
    { id: 'b', name: 'Split pane', bet: 'Evidence needs permanent real estate to actually get read.', sacrifice: '~9 rows visible instead of ~17.', steals: 'Superhuman / Ashby review mode' },
    { id: 'c', name: 'Criteria grid', bet: 'Comparison is the real job, so the list should be the comparison.', sacrifice: 'Very few distinct ranks — and the brief asks for a ranked list.', steals: 'Hebbia Matrix / Juicebox 3-state' },
  ],
  outreach: [
    { id: 'a', name: 'Grouped table', bet: 'Group by who is being waited on; needs-you first.', sacrifice: 'Still a list you can browse instead of clear.', steals: 'Front Open/Later/Done' },
    { id: 'b', name: 'Queue + pipeline strip', bet: 'Decide one at a time, with the whole pipeline in peripheral vision; the board expands in place when the queue empties.', sacrifice: 'While triaging, a column is a count and a row of faces — not readable cards.', steals: 'Superhuman triage · Greenhouse who-is-blocking colour · Ashby review mode' },
    { id: 'c', name: 'Pipeline board', bet: 'Built to be disproven: the affordance lies.', sacrifice: '4× the width for the same information.', steals: 'Greenhouse visual pipeline' },
  ],
};
